/**
 * Reads the real per-agent settings/config files under `homeDir` into the
 * plain facts `domain/setup-plan.ts#detectAgents` expects. Never throws: a
 * missing or malformed file reads as absent, exactly like
 * `adapters/tui-config.ts#readTuiConfig` and kankaku's own
 * `hub-credentials.ts#readCredentialsFile`.
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import { join } from "node:path";
import type { AgentDetectionFacts, ClaudeSettingsFacts, ConfigFileFacts, SettingsPackagesFacts } from "../../domain/setup-plan.ts";
import { entrySource } from "../../domain/kankaku-package.ts";
import { buildCommandFileContent, ourCommandFileRoot, ourHookCommandMatch } from "../../domain/claude-integration.ts";
import type { CommandMatch } from "../../domain/claude-integration.ts";
import { commandsDirectory, readPluginCommands } from "./claude-commands.ts";
import type { PluginCommand } from "./claude-commands.ts";
import { buildSettingsHooks, locateClaudePlugin, readPluginHooks } from "./claude-plugin.ts";
import type { HookEventEntry, PluginHooks } from "./claude-plugin.ts";
import { isOurHookEntry, statusLineCommand } from "./claude.ts";

function readJsonObject(filePath: string): Record<string, unknown> | undefined {
  if (!existsSync(filePath)) return undefined;
  try {
    const parsed: unknown = JSON.parse(readFileSync(filePath, "utf8"));
    if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) return undefined;
    return parsed as Record<string, unknown>;
  } catch {
    return undefined;
  }
}

function readSettingsPackages(settingsPath: string): SettingsPackagesFacts | undefined {
  const parsed = readJsonObject(settingsPath);
  if (!parsed) return undefined;
  const entries: unknown[] = Array.isArray(parsed["packages"]) ? parsed["packages"] : [];
  const packages = entries.map(entrySource).filter((source): source is string => source !== undefined);
  return { settingsPath, packages };
}

/** Scans every event's hook entries for a command that is one of kankaku's own (see `domain/claude-integration.ts#ourHookCommandMatch`), returning the first match (root + whether it's the legacy `/src/hook.ts` form), or `undefined` when none is found. */
function extractHooksMatch(parsed: Record<string, unknown>): CommandMatch | undefined {
  const hooks = parsed["hooks"];
  if (!hooks || typeof hooks !== "object" || Array.isArray(hooks)) return undefined;
  for (const entries of Object.values(hooks as Record<string, unknown>)) {
    if (!Array.isArray(entries)) continue;
    for (const entry of entries) {
      if (!entry || typeof entry !== "object") continue;
      const innerHooks = (entry as Record<string, unknown>)["hooks"];
      if (!Array.isArray(innerHooks)) continue;
      for (const hook of innerHooks) {
        if (!hook || typeof hook !== "object") continue;
        const command = (hook as Record<string, unknown>)["command"];
        if (typeof command !== "string") continue;
        const match = ourHookCommandMatch(command);
        if (match !== undefined) return match;
      }
    }
  }
  return undefined;
}

type ClaudeDrift = Pick<
  ClaudeSettingsFacts,
  "statusLineOutdated" | "hooksMissingEvents" | "hooksOutdatedEvents" | "commandsMissing" | "commandsOutdated" | "commandsStale" | "pluginError"
>;

/** Reads a generated command file's bytes, or `undefined` when absent/unreadable. */
function readFileOrUndefined(file: string): string | undefined {
  try {
    return readFileSync(file, "utf8");
  } catch {
    return undefined;
  }
}

/**
 * Compares what is installed with what the plugin at the resolved root
 * expects (`override` or the bundled package): the exact statusLine
 * command, every plugin event's hook entries of ours (same command,
 * matcher and timeout — foreign entries are ignored), every
 * `commands/*.md` generated byte-identically, and no stale generated file.
 * A foreign file where a command would go is not drift (setup never
 * touches it). When the plugin cannot be read, only `pluginError` is set.
 */
function readClaudeDrift(homeDir: string, parsed: Record<string, unknown>, override: string | undefined): ClaudeDrift {
  let root: string;
  let expectedHooks: PluginHooks;
  let commands: PluginCommand[];
  try {
    root = locateClaudePlugin(override).root;
    expectedHooks = buildSettingsHooks(root, readPluginHooks(root));
    commands = readPluginCommands(root);
  } catch (error) {
    return { pluginError: error instanceof Error ? error.message : String(error) };
  }

  const statusLine = parsed["statusLine"];
  const currentCommand =
    statusLine && typeof statusLine === "object" && !Array.isArray(statusLine) ? (statusLine as Record<string, unknown>)["command"] : undefined;
  const statusLineOutdated = typeof currentCommand === "string" && currentCommand !== statusLineCommand(root);

  const hooks = parsed["hooks"];
  const currentHooks = hooks && typeof hooks === "object" && !Array.isArray(hooks) ? (hooks as Record<string, unknown>) : {};
  const hooksMissingEvents: string[] = [];
  const hooksOutdatedEvents: string[] = [];
  for (const [event, desired] of Object.entries(expectedHooks)) {
    const entries = Array.isArray(currentHooks[event]) ? (currentHooks[event] as HookEventEntry[]) : [];
    const ours = entries.filter(isOurHookEntry);
    if (ours.length === 0) hooksMissingEvents.push(event);
    else if (JSON.stringify(ours) !== JSON.stringify(desired)) hooksOutdatedEvents.push(event);
  }

  const dir = commandsDirectory(homeDir);
  const commandsMissing: string[] = [];
  const commandsOutdated: string[] = [];
  const wanted = new Set<string>();
  for (const command of commands) {
    wanted.add(`${command.name}.md`);
    const existing = readFileOrUndefined(join(dir, `${command.name}.md`));
    if (existing === undefined) commandsMissing.push(command.name);
    else if (existing !== buildCommandFileContent(root, command.source) && ourCommandFileRoot(existing) !== undefined) commandsOutdated.push(command.name);
  }
  const commandsStale: string[] = [];
  let entries: string[] = [];
  try {
    entries = readdirSync(dir).sort();
  } catch {
    // no directory: nothing stale
  }
  for (const entry of entries) {
    if (wanted.has(entry) || !entry.endsWith(".md")) continue;
    const content = readFileOrUndefined(join(dir, entry));
    if (content !== undefined && ourCommandFileRoot(content) !== undefined) commandsStale.push(entry.slice(0, -".md".length));
  }

  return { statusLineOutdated, hooksMissingEvents, hooksOutdatedEvents, commandsMissing, commandsOutdated, commandsStale };
}

function readClaudeSettings(settingsPath: string, homeDir: string, override: string | undefined): ClaudeSettingsFacts | undefined {
  const parsed = readJsonObject(settingsPath);
  if (!parsed) return undefined;
  const statusLine = parsed["statusLine"];
  const command =
    statusLine && typeof statusLine === "object" && !Array.isArray(statusLine) && typeof (statusLine as Record<string, unknown>)["command"] === "string"
      ? ((statusLine as Record<string, unknown>)["command"] as string)
      : undefined;
  const hooksMatch = extractHooksMatch(parsed);
  return {
    settingsPath,
    statusLineCommand: command,
    hooksRoot: hooksMatch?.root,
    hooksLegacy: hooksMatch?.legacy ?? false,
    ...readClaudeDrift(homeDir, parsed, override),
  };
}

function readConfigFilePresence(configPath: string): ConfigFileFacts | undefined {
  return existsSync(configPath) ? { configPath } : undefined;
}

/** Read every agent's settings/config file under `homeDir`, tolerating any absence or malformed content. `claudePluginDir` overrides the bundled kankaku-claude plugin root the Claude Code install is compared against. */
export function readAgentFacts(homeDir: string, claudePluginDir?: string): AgentDetectionFacts {
  return {
    pi: readSettingsPackages(join(homeDir, ".pi", "agent", "settings.json")),
    gentleShell: readSettingsPackages(join(homeDir, ".gentle-shell", "agent", "settings.json")),
    claudeCode: readClaudeSettings(join(homeDir, ".claude", "settings.json"), homeDir, claudePluginDir),
    codex: readConfigFilePresence(join(homeDir, ".codex", "config.toml")),
    opencode: readConfigFilePresence(join(homeDir, ".config", "opencode", "opencode.json")),
  };
}
